trigger:
  branches:
    include:
    - master
  paths:
    include:
    - typescript/*

stages:
- stage: Compliance
  jobs:
  - job: 
    steps:
    - task: ComponentGovernanceComponentDetection@0
      inputs:
        scanType: 'Register'
        verbosity: 'Verbose'
        alertWarningLevel: 'High'

- stage: TypeScript
  jobs:
    - template: azure-pipelines-template.yaml