parameters:
  nodeVersion: ["8", "10"]
  operatingSystems: ["ubuntu-16.04", 'macos-10.13', 'vs2017-win2016']

jobs:
- job:
  displayName: 'TypeScript'
  strategy:
    matrix:
      ${{ each node in parameters.nodeVersion }}:
          ${{ each os in parameters.operatingSystems }}:
            ${{ format(' {0} - {1}', node, os) }}:
              imageName: ${{ os }}
              node.version: ${{ node }}

  pool:
    vmImage: $(imageName)

  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '$(node.version)'

  - script: |
      cd typescript 
      npm install
    displayName: 'Install dependencies'

  - script: |
      cd typescript 
      npm run test:prod
    displayName: 'Tests'

  - script: |
      cd typescript 
      npm run build
    displayName: 'Build'

  - task: PublishTestResults@2
    condition: succeededOrFailed()
    inputs:
      testResultsFiles: '**/test-report.xml'
      testRunTitle: 'Test results for npm test'

  - task: PublishCodeCoverageResults@1
    inputs: 
      codeCoverageTool: Cobertura
      summaryFileLocation: '$(System.DefaultWorkingDirectory)/**/cobertura-coverage.xml'