trigger:
  branches:
    include:
    - master
  paths:
    include:
    - dotnet/*

stages:
- stage: Compliance
  jobs:
  - job: 
    steps:
    - task: ComponentGovernanceComponentDetection@0
      inputs:
        scanType: 'Register'
        verbosity: 'Verbose'
        alertWarningLevel: 'High'

- stage: DotNetDesktop
  jobs:
  - job:        
    pool:
      vmImage: 'windows-2019'
    steps:    
      - script: |
          cd dotnet
          dotnet restore
        displayName: NuGet Restore

      - task: VSBuild@1
        inputs:
          solution: dotnet/Workspace.sln
          restoreNugetPackages: true
      
      - task: VSTest@2
        inputs:
          testSelector: 'testAssemblies'
          testAssemblyVer2: |
            '**\Microsoft.WorkspaceTest.Desktop.dll'
            '**\Microsoft.WorkspaceTest.dll'
          codeCoverageEnabled: True